import pytest
from ._helpers import create_test_namelist_dict, ROMSConfiguration, ROMS_ROOT, get_summary_value


@pytest.fixture()
def standard_configuration(tmp_path_factory, read_cppdefs) -> ROMSConfiguration:
    """Generates a session-scoped ROMSConfiguration using the default cppkey set"""

    cpp_keys=read_cppdefs(ROMS_ROOT/"src/cppdefs.opt")
    build_dir = tmp_path_factory.mktemp("standard_configuration_build")
    conf = ROMSConfiguration(cpp_keys=cpp_keys, location=build_dir)
    conf.compile()
    return conf

@pytest.fixture()
def read_cppdefs():
    """Simple fixture to read a cppdefs.opt file from a ROMS configuration.

    Requires that each key starts with 'define' and that the first character is not a !
    """
    def _read_cppdefs(fname):
        cppkeys = []
        with open(fname,"r") as cppfile:
            cpplines = cppfile.readlines()
        for line in cpplines:
            thisline = line.lower().strip()
            if ("define" in thisline) and (thisline[0]!="!"):
                thiskey = thisline.split("define")[-1].split("!")[0]
                cppkeys.append(thiskey.strip().upper())
        return cppkeys
    return _read_cppdefs


def test_default_cppkeys(read_cppdefs):
    """Test that the default cpp key set found at $ROMS_ROOT/src/cppdefs.opt is unchanged.

    Force the user to manually update a list in this test if the change was expected.
    """
    expected_cpp_keys=[
        'EXACT_RESTARTS', 'NONLIN_EOS', 'SALINITY', 'SOLVE3D', 'SPLIT_EOS', 'TIDES', 'UV_ADV', 'UV_COR',
        'CURVGRID', 'MASKING', 'SPHERICAL', 'SPONGE', 'BULK_FRC', 'M2_FRC_BRY', 'M3_FRC_BRY', 'OBC_EAST',
        'OBC_M2FLATHER', 'OBC_M3ORLANSKI', 'OBC_NORTH', 'OBC_SOUTH', 'OBC_TORLANSKI', 'OBC_WEST', 'T_FRC_BRY',
        'Z_FRC_BRY', 'LMD_BKPP', 'LMD_KPP', 'LMD_MIXING', 'LMD_NONLOCAL', 'LMD_RIMIX', 'TS_DIF2', 'UV_VIS2',
        'MARBL', 'MARBL_DIAGS', 'NHY_FORCING', 'NOX_FORCING', 'PCO2AIR_FORCING']
    default_cpp_keys = read_cppdefs(ROMS_ROOT/"src/cppdefs.opt")
    assert (expected_cpp_keys == default_cpp_keys)

def test_exact_restart(standard_configuration,input_dir,tmp_path):
    """Test that exact restarts work correctly in ROMS.

    Runs the standard configuration twice: once for 20 time-steps from an initial file,
    (generating a restart file every 10 time-steps), then again for 10 times-steps starting
    from a restart file generated by the previous run.

    The final restart files for both runs are then compared for parity.
    """

    # Generate a namelist for both runs
    nml = create_test_namelist_dict(input_dir)
    nml["TIME_STEPPING"]["dt"] = 40
    nml["BASIC_OUTPUT_SETTINGS"]["output_period_his"] = 400
    nml["BASIC_OUTPUT_SETTINGS"]["wrt_file_rst"] = True
    nml["BASIC_OUTPUT_SETTINGS"]["output_period_rst"] = 400
    nml["BASIC_OUTPUT_SETTINGS"]["nrpf_rst"] = 2
    nml["BGC_SETTINGS"]["output_period_bgc_his"] = 400
    nml["FORCING_FILES"] = {
        "frcfiles": [
            str(input_dir / "example_input_boundary_forcing.nc"),
            str(input_dir / "example_input_surface_forcing.nc"),
            str(input_dir / "example_input_bgc_surface_forcing.nc"),
            str(input_dir / "example_input_co2_surface_forcing.nc"),
            str(input_dir / "example_input_river_forcing.nc"),
            str(input_dir / "example_input_bgc_boundary_forcing.nc"),
        ]
    }
    nml["PARAM_SETTINGS"]["nt_bgc"] = 32

    # Run 1: Produce 2 restart files from init
    run1_path = (tmp_path/"run_1/")
    run1_path.mkdir()

    standard_configuration.run(nml,cwd=run1_path)

    # Run 2: Produce 1 restart file from run 1's restart
    run2_path = (tmp_path/"run_2/")
    run2_path.mkdir()

    nml["INITIAL_CONDITIONS"]["inifile"] = str(run1_path/"roms_rst.20100101000640.nc")
#    nml["INITIAL_CONDITIONS"]["nrrec"] = 2
    nml["TIME_STEPPING"]["ntimes"] = 10

    standard_configuration.run(nml, cwd=run2_path)

    # Compare restart file contents (without time-step var, which records record no. since init):
    run1_val = get_summary_value(test_dir=run1_path,
                                 prefix="roms_rst.20100101001320",
                                 vars_to_exclude=["time_step",])
    run2_val = get_summary_value(test_dir=run2_path,
                                 prefix="roms_rst.20100101001320",
                                 vars_to_exclude=["time_step",])
    assert (run1_val == run2_val)

