name: Automated Testing (gfortran, containerized)

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cworthy-ocean/marbl_gnu_mpich:0.1
    strategy:
      fail-fast: false
    name: pytest_gnu
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Environment Variables
      run: |
        ROMS_ROOT=$(pwd)
        echo "ROMS_ROOT=$ROMS_ROOT" >> $GITHUB_ENV
        echo "PATH=./:$PATH:$ROMS_ROOT/Tools-Roms" >> $GITHUB_ENV
      shell: bash
    - name: Print system info
      run: lscpu
    - name: Compile Fortran Code
      shell: bash
      run: |
        micromamba run -n roms-ci bash -c '
        cd Work/
        cd ${ROMS_ROOT}/Tools-Roms/
        make partit COMPILER=gnu
        '

    - name: Run tests
      shell: bash
      run: |
        micromamba run -n roms-ci bash -c '
        cd ${ROMS_ROOT}/tests/${{ matrix.example}}/
        pytest . --environ=ifx
        '
