name: Automated Testing (ifx, containerized)

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cworthy-ocean/marbl_ifx_openmpi:0.1
    strategy:
      fail-fast: false
    name: pytest_ifx
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        shell: bash
        run: |
          ROMS_ROOT=$(pwd)
          echo "ROMS_ROOT=$ROMS_ROOT" >> $GITHUB_ENV
          echo "PATH=./:$PATH:$ROMS_ROOT/Tools-Roms" >> $GITHUB_ENV
      - name: Print system info
        run: lscpu

      - name: Compile Fortran Code
        shell: bash
        run: |
          source $GITHUB_ENV
          cd Work/
          cd ${ROMS_ROOT}/Tools-Roms/
          make partit COMPILER=intel

      - name: Run tests
        shell: bash
        run: |
          source $GITHUB_ENV
          cd $ROMS_ROOT/tests/
          pytest . --environ=ifx

